Tutorial on installing aiware on local environment
veritone/docs pull request #1181
Opened 2021-06-20 14:34 UTC by hm90121

2021-06-21 06:01 UTC, LevLevenberg approved these changes
LGTM

2021-06-21 09:03 UTC, LevLevenberg requested changes

2021-06-21 09:03 UTC, LevLevenberg commented on src/docs/tutorials/pages/install-aiware-on-local-environment.md
> +{"errors":[{"data":{"requestId":"AC110001:81E8_AC11000B:2328_60CCCF4C_013D:0023","contentType":"not set","errorId":"9fa4a6c2-ee6f-419d-a5ba-c5e16dcb63e2"},"name":"invalid_input","message":"The HTTP r
@hm90121 why do we provide an error as an indicator of a successful setup? Can't it be something more friendly?

2021-06-21 12:55 UTC, hm90121 commented on src/docs/tutorials/pages/install-aiware-on-local-environment.md
> +{"errors":[{"data":{"requestId":"AC110001:81E8_AC11000B:2328_60CCCF4C_013D:0023","contentType":"not set","errorId":"9fa4a6c2-ee6f-419d-a5ba-c5e16dcb63e2"},"name":"invalid_input","message":"The HTTP r
well it can be a friendly response i can change that()  but this step only concludes that the server is responding(not abour graphql syntax)

2021-06-21 13:41 UTC, LevLevenberg commented on src/docs/tutorials/pages/install-aiware-on-local-environment.md
> +{"errors":[{"data":{"requestId":"AC110001:81E8_AC11000B:2328_60CCCF4C_013D:0023","contentType":"not set","errorId":"9fa4a6c2-ee6f-419d-a5ba-c5e16dcb63e2"},"name":"invalid_input","message":"The HTTP r
@hm90121  I realize that. Yet, think of a user experience here. He follows a very detailed and well explained tutorial and finally gets an error response... a bit disappointing ... We want 100% success, so the details a very important here.

2021-06-21 13:44 UTC, hm90121 commented on src/docs/tutorials/pages/install-aiware-on-local-environment.md
> +{"errors":[{"data":{"requestId":"AC110001:81E8_AC11000B:2328_60CCCF4C_013D:0023","contentType":"not set","errorId":"9fa4a6c2-ee6f-419d-a5ba-c5e16dcb63e2"},"name":"invalid_input","message":"The HTTP r
ok,will change the respone

2021-06-22 06:03 UTC, LevLevenberg approved these changes
Great Job

2021-06-22 06:03 UTC, merged