Added two tutorials
veritone/docs pull request #1204
Opened 2021-06-23 17:52 UTC by ClarytyLLC

The following tutorials are added:
Adding Custom Fields
Working with Jobs.

2021-07-21 21:29 UTC, myoungerman commented on src/docs/automate-studio/README.md
> +> More Tutorials are coming up soon
Please delete line 433. Once those tutorials are ready, we can add links to them here if this is a good spot.

2021-07-21 21:37 UTC, myoungerman commented on src/docs/_sidebar.md
>    - [Install aiWARE on local environment](/tutorials/pages/install-aiware-on-local-environment.md)
Please fix the indentation of this item by moving it up a level in the hierarchy (so on the same level as the **Tutorials** section. Right now, the sidebar is formatted incorrectly because this item is considered a child of the **Tutorials** section.

2021-07-21 21:43 UTC, myoungerman commented on src/docs/automate-studio/application/README.md
> +Canvas is the gridded workspace in the center of the Automate Studio App, where we design and run flows. It is organized by tabs located at the top - one for each individual flow. We do not need to d
Find and replace "we" with "you".

2021-07-21 21:45 UTC, myoungerman commented on src/docs/automate-studio/getting-started/README.md
> +We will learn to quickly build our first flow in just a few minutes with this quickstart guide of Automate Studio.
Replace "we" with "you".

2021-07-21 21:48 UTC, myoungerman commented on src/docs/automate-studio/getting-started/README.md
> +## Step 2: Add Nodes to Our Flow
Restore the previous version.

2021-07-21 21:50 UTC, myoungerman commented on src/docs/automate-studio/getting-started/README.md
> +4. Click the **Done** button to save our changes.
Change "our" to "your".

2021-07-21 22:01 UTC, myoungerman commented on src/docs/automate-studio/getting-started/README.md
> +1. Click the little _bug_ icon in the information pane, on the right, to enable the display of debug messages.
Delete "little".

2021-07-21 22:01 UTC, myoungerman commented on src/docs/automate-studio/getting-started/README.md
> +Congratulations on building and running your first flow engine using Automate Studio!!
Use only one exclamation point.

2021-07-21 22:02 UTC, myoungerman commented on src/docs/automate-studio/tutorials/basic/object-detection/tutorial.md
> +At the end of the tutorial, we would have created a flow that looks like:
Replace "we would" with "you'll"

2021-07-21 22:06 UTC, myoungerman commented on src/docs/automate-studio/tutorials/basic/object-detection/tutorial.md
> +Let us configure the flow to catch errors and help us debug errors.
Replace "let us" with "You'll".

2021-07-21 22:12 UTC, myoungerman commented on src/docs/automate-studio/tutorials/basic/transcription/tutorial.md
> +At the end of the tutorial, we would have created a flow that looks like:
Replace "we would" with "you'll".

2021-07-21 22:15 UTC, myoungerman commented on src/docs/tutorials/pages/adding-custom-fields.md
> +We can create the custom fields inside of VBA either when creating a new engine or on the details page of an existing engine.
Replace "we" with "you".

2021-07-21 22:17 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +After review, the build status changes to *Approved* or *Disapproved*. If the build is Approved, then it can be hosted in the aiWARE platform and deployed at any time. If the build was Disapproved, t
Fix spelling.

2021-07-21 22:17 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +Once you engine is approved, you can view it on the Veritone platform. The engine can be deployed and made available to users in the aiWARE platform. Users can then submit jobs to the engine on the p
your

2021-07-21 22:19 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +3. Click on the engine's name to see the Builds page. If there are no uploaded builds, then the page will show **Create a New Build** option with the instructions to cerate a build.
Spelling

2021-07-21 22:20 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +   If there are uploaded builds available, then we will see a list of them, along with status information for each one:
Replace with "and".

2021-07-21 22:21 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +4. The **Create a New Build** checklist starts with "Include your manifest with your build" that should have been completed by now. For more information, about building the manifest see [creating man
Rewrite this so it tells you who should have completed that task.

2021-07-21 22:21 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +4. The **Create a New Build** checklist starts with "Include your manifest with your build" that should have been completed by now. For more information, about building the manifest see [creating man
Remove ,

2021-07-21 22:21 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +We will next tag our build and push it for approval.
Replace with "Now you'll tag your"

2021-07-21 22:23 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +1.  We will run the following command to tag the engine, where custom-tag is the tag we will use to recognize our build:
Bold "custom-tag" if it's the name of something the user will reference.

2021-07-21 22:25 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +We are notified (within 72 hours) as to the status of the engine. If the engine is Approved, we can Deploy it immediately. If not, then we will have to take appropriate steps to address any problems.
Change "Approved" to lowercase.

2021-07-21 22:26 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +- **Vulnerability Issues**: If the engine failed certification due to a critical security vulnerability, then we must try updating the docker base image in teh Dockerfile. Best is to use the `latest`
spelling

2021-07-21 22:26 UTC, myoungerman commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +- **Vulnerability Issues**: If the engine failed certification due to a critical security vulnerability, then we must try updating the docker base image in teh Dockerfile. Best is to use the `latest`
Replace "Best" with "The best practice".

2021-07-21 22:36 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +>**Tip** Before getting started, we recommend to read about [training an engine](#training-an-engine) and [working with jobs](#working-with-jobs).
Replace with "reading"

2021-07-21 22:37 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +In this tutorial we will learn together how to use TDOs. In aiWARE, jobs and job-related artifacts (such as media files) need to be associated with a container called a [Temporal Data Object (TDO)](h
Remove "together"

2021-07-21 22:37 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +In this tutorial we will learn together how to use TDOs. In aiWARE, jobs and job-related artifacts (such as media files) need to be associated with a container called a [Temporal Data Object (TDO)](h
Remove ,

2021-07-21 22:38 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +- We must [delete a TDO](#step4-delete-a-tdo-and-all-assets) or [purge its contents](#step-3-remove-tdo-content) when we do not need the TDO; else, it lives permanently.
Remove "; else, it lives permanently."

2021-07-21 22:39 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +By the end of this tutorial, we would have learnt how to create, manage, and then delete a TDO.
Replace "we would" with "you'll".

2021-07-21 22:40 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +GraphQL lets you [create a blank TDO](#step-1-create-a-blank-tdo) or [create a TDO and upload and asset](#create_a_tdo_and_upload_asset) to it.
Change "and" to "an".

2021-07-21 22:40 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +The first step in the job workflow is to create a TDO. We can create a TDO by simply the following mutation in GraphQL.
Missing a verb in "simply the".

2021-07-21 22:40 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +The `startDateTime` and `stopDateTime` values are required. We can provide any values but the stopdatetime must be after startdatetime.  The stopdatetime should not be more than an year of the the st
Rewrite "more than an year".

2021-07-21 22:42 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +This query displays the debug or log information reported by the engine at the completion of the task
Missing punctuation.

2021-07-21 22:43 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +Once we are done working with the TDO, we can remove only the content associated with a TDO. This does not remove the TDO and asset metadata. We must run the `cleanupTDO` mutation with the TDO `id`.
Why does the reader have to run this mutation? What's it do?

2021-07-21 22:43 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +Here is a Below is a sample request to remove TDO Content :
Fix wording

2021-07-21 22:44 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +We can remove a TDO and all its asset metadata, by requesting to `deleteTDO` mutation with the TDO `id`. The operation is processed immediately after the request and permanently deletes the TDO *as w
Remove ,

2021-07-21 22:45 UTC, myoungerman commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +We can remove a TDO and all its asset metadata, by requesting to `deleteTDO` mutation with the TDO `id`. The operation is processed immediately after the request and permanently deletes the TDO *as w
Requesting to do what with the mutation? Run it?

2021-07-21 22:48 UTC, myoungerman requested changes
Hi @ClarytyLLC, I've left comments for spelling, grammar, and other necessary changes. A big required change is switching from "we" and similar wording to "you" or "you'll". To save time, I recommend doing a find and replace in VSCode or whatever code editor you're using. Please message me if you have any questions!

2021-07-22 17:22 UTC, ClarytyLLC commented on src/docs/automate-studio/application/README.md
> +Canvas is the gridded workspace in the center of the Automate Studio App, where we design and run flows. It is organized by tabs located at the top - one for each individual flow. We do not need to d
Fixed

2021-07-22 17:23 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +We will learn to quickly build our first flow in just a few minutes with this quickstart guide of Automate Studio.
Done

2021-07-22 17:26 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +4. Click the **Done** button to save our changes.
Fixed

2021-07-22 17:26 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +## Step 2: Add Nodes to Our Flow
Fixed

2021-07-22 17:27 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +1. Click the little _bug_ icon in the information pane, on the right, to enable the display of debug messages.
Fixed

2021-07-22 17:27 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +Congratulations on building and running your first flow engine using Automate Studio!!
Fixed

2021-07-22 17:29 UTC, ClarytyLLC commented on src/docs/automate-studio/tutorials/basic/object-detection/tutorial.md
> +At the end of the tutorial, we would have created a flow that looks like:
Fixed

2021-07-22 17:30 UTC, ClarytyLLC commented on src/docs/automate-studio/tutorials/basic/object-detection/tutorial.md
> +Let us configure the flow to catch errors and help us debug errors.
Fixed

2021-07-22 17:36 UTC, ClarytyLLC commented on src/docs/automate-studio/tutorials/basic/transcription/tutorial.md
> +At the end of the tutorial, we would have created a flow that looks like:
Fixed

2021-07-22 17:37 UTC, ClarytyLLC commented on src/docs/tutorials/pages/adding-custom-fields.md
> +We can create the custom fields inside of VBA either when creating a new engine or on the details page of an existing engine.
Fixed

2021-07-22 17:40 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +After review, the build status changes to *Approved* or *Disapproved*. If the build is Approved, then it can be hosted in the aiWARE platform and deployed at any time. If the build was Disapproved, t
Fixed

2021-07-22 17:42 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +Once you engine is approved, you can view it on the Veritone platform. The engine can be deployed and made available to users in the aiWARE platform. Users can then submit jobs to the engine on the p
Fixed

2021-07-22 17:42 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +3. Click on the engine's name to see the Builds page. If there are no uploaded builds, then the page will show **Create a New Build** option with the instructions to cerate a build.
Fixed

2021-07-22 17:44 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +   If there are uploaded builds available, then we will see a list of them, along with status information for each one:
Changed

2021-07-22 17:48 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +4. The **Create a New Build** checklist starts with "Include your manifest with your build" that should have been completed by now. For more information, about building the manifest see [creating man
Fixed.

2021-07-22 17:49 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +4. The **Create a New Build** checklist starts with "Include your manifest with your build" that should have been completed by now. For more information, about building the manifest see [creating man
Fixed

2021-07-22 17:50 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +We will next tag our build and push it for approval.
Fixed

2021-07-22 17:52 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +1.  We will run the following command to tag the engine, where custom-tag is the tag we will use to recognize our build:
Fixed

2021-07-22 17:54 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +We are notified (within 72 hours) as to the status of the engine. If the engine is Approved, we can Deploy it immediately. If not, then we will have to take appropriate steps to address any problems.
Fixed

2021-07-22 17:55 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +- **Vulnerability Issues**: If the engine failed certification due to a critical security vulnerability, then we must try updating the docker base image in teh Dockerfile. Best is to use the `latest`
Fixed

2021-07-22 17:56 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +>**Tip** Before getting started, we recommend to read about [training an engine](#training-an-engine) and [working with jobs](#working-with-jobs).
Fixed

2021-07-22 17:56 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +In this tutorial we will learn together how to use TDOs. In aiWARE, jobs and job-related artifacts (such as media files) need to be associated with a container called a [Temporal Data Object (TDO)](h
Fixed

2021-07-22 17:58 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +- We must [delete a TDO](#step4-delete-a-tdo-and-all-assets) or [purge its contents](#step-3-remove-tdo-content) when we do not need the TDO; else, it lives permanently.
Fixed

2021-07-22 17:59 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +By the end of this tutorial, we would have learnt how to create, manage, and then delete a TDO.
fixed

2021-07-22 18:00 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +GraphQL lets you [create a blank TDO](#step-1-create-a-blank-tdo) or [create a TDO and upload and asset](#create_a_tdo_and_upload_asset) to it.
Fixed

2021-07-22 18:00 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +The first step in the job workflow is to create a TDO. We can create a TDO by simply the following mutation in GraphQL.
Fixed

2021-07-22 18:01 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +The `startDateTime` and `stopDateTime` values are required. We can provide any values but the stopdatetime must be after startdatetime.  The stopdatetime should not be more than an year of the the st
Fixed

2021-07-22 18:02 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +This query displays the debug or log information reported by the engine at the completion of the task
Fixed

2021-07-22 18:05 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +Once we are done working with the TDO, we can remove only the content associated with a TDO. This does not remove the TDO and asset metadata. We must run the `cleanupTDO` mutation with the TDO `id`.
Fixed

2021-07-22 18:05 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +Here is a Below is a sample request to remove TDO Content :
FIxed

2021-07-22 18:05 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +We can remove a TDO and all its asset metadata, by requesting to `deleteTDO` mutation with the TDO `id`. The operation is processed immediately after the request and permanently deletes the TDO *as w
Fixed

2021-07-22 18:07 UTC, ClarytyLLC commented on src/docs/tutorials/pages/using-temporal-data-objects.md
> +We can remove a TDO and all its asset metadata, by requesting to `deleteTDO` mutation with the TDO `id`. The operation is processed immediately after the request and permanently deletes the TDO *as w
Fixed

2021-07-22 18:07 UTC, ClarytyLLC commented on src/docs/tutorials/pages/how-to-get-engine-approved.md
> +- **Vulnerability Issues**: If the engine failed certification due to a critical security vulnerability, then we must try updating the docker base image in teh Dockerfile. Best is to use the `latest`
Fixed

2021-07-22 18:08 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +We will learn to quickly build our first flow in just a few minutes with this quickstart guide of Automate Studio.
Fixed

2021-07-22 18:08 UTC, ClarytyLLC commented on src/docs/automate-studio/application/README.md
> +Canvas is the gridded workspace in the center of the Automate Studio App, where we design and run flows. It is organized by tabs located at the top - one for each individual flow. We do not need to d
Fixed

2021-07-22 18:11 UTC, ClarytyLLC commented on src/docs/_sidebar.md
>    - [Install aiWARE on local environment](/tutorials/pages/install-aiware-on-local-environment.md)
Fixed

2021-07-22 18:11 UTC, ClarytyLLC commented on src/docs/automate-studio/README.md
> +> More Tutorials are coming up soon
Fixed

2021-07-23 15:10 UTC, myoungerman commented on src/docs/_sidebar.md
> +  - [How to get your engine approved](/tutorials/pages/how-to-get-egine-approved.md)
Line 234 engine is misspelled, causing a 404 error.

2021-07-23 15:12 UTC, myoungerman commented on src/docs/_sidebar.md
>    - [Install aiWARE on local environment](/tutorials/pages/install-aiware-on-local-environment.md)
When I preview the page using the latest preview link, I still see a large gap between **Tutorials** and the *Install aiWARE on local environment**. Do you see that gap when you preview the page, or is it just me?

2021-07-26 06:36 UTC, ClarytyLLC commented on src/docs/_sidebar.md
> +  - [How to get your engine approved](/tutorials/pages/how-to-get-egine-approved.md)
Apologies. I have fixed it now.

2021-07-26 06:40 UTC, ClarytyLLC commented on src/docs/_sidebar.md
>    - [Install aiWARE on local environment](/tutorials/pages/install-aiware-on-local-environment.md)
I see that the comments are causing those gaps. I have fixed that now. Please check in the preview and let me know if the issue persists.

2021-07-26 17:17 UTC, myoungerman approved these changes

2021-07-26 18:07 UTC, myoungerman commented
@ClarytyLLC Thanks for the changes! Everything looks good now, please resolve the merge conflicts and then you can merge the PR :)

2021-07-28 22:26 UTC, myoungerman commented
Closing this PR since I copied it to [1351](https://github.com/veritone/docs/pull/1351) to resolve merge conflicts.

2021-07-28 22:27 UTC, closed without merging