build engine using developer app tutorial
veritone/docs pull request #1280
Opened 2021-07-09 15:51 UTC by hm90121

2021-07-09 22:07 UTC, kevmurray requested changes

2021-07-09 22:07 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +4.Now create a new build specifying the docker image url for the image which in this case  is hello world so the path would be
Hmm - this is hard because this step is totally wrong in virtually every possible way it could be wrong. And the reason it is wrong is because we just rewrote this part of the system last week and it doesn't actually work right now - the instructions in the screen shot are technically correct, but lack detail.

Remember earlier, when I said that there was a whole section missing between steps 2 and 3? Well that section is what you need to make this step possible, and it's probably another 7-10 steps. The other tutorial I referenced describes how to build the docker image, but we also need to create an account on docker hub and upload the image there. The name of that uploaded image is what you actually need to use here in step 4, and it's not `docker.veritone.com/hello-world` - it's actually the name of the image you upload to your personal account on docker hub.

I'm not sure how to communicate all the details to you or when I'll have time. How are you currently learning the details of complex systems you need to document?

2021-07-09 22:07 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +One of the easiest ways to do this is, of course, to use the [GraphQL Playground](https://api.veritone.com/v3/graphq) web IDE.
this URL is not valid - use `https://api.veritone.com/v3/graphql`

2021-07-09 22:07 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +1. Navigate to the [GraphQL Sandbox IDE](https://api.veritone.com/v3/graphql).
Why do you call this the "GraphQL Playground" in the previous line and "GraphQL Sandbox IDE" in this line? Pick one term and stick with it

2021-07-09 22:07 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +   ![Graphql-Engine](graphql-engine.png)
This screen shot shows you in the middle of executing queries - replace this screenshot with the default, empty window like the customer would see if they clicked on the link for the first time.

2021-07-14 17:26 UTC, kevmurray commented
@hm90121 , you are doing a lot of commits to this PR - please put into "draft mode" until you are done (assuming draft mode doesn't interfere with vercel)

2021-07-14 17:39 UTC, hm90121 commented
> @hm90121 , you are doing a lot of commits to this PR - please put into "draft mode" until you are done (assuming draft mode doesn't interfere with vercel)
> 
> > oops, looks like you may have finalized this recently

yes this is final

2021-07-19 20:25 UTC, kevmurray requested changes

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +Here is a screenshot of the sample manifest in the terminal:
Delete this screenshot because
1. It is wrong
2. It is pretty much just a copy of the last screenshot
3. It exposes GNU nano as an editor, which is not relevant to the tutorial

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +7. Tag the hello-world engine using the command below:
I'm not comfortable with this layout since it provides an example that uses "veritone" as the account name, which is going to be confusing. Can you update the instructions with an example account name on docker hub (like "my-docker-account" or something that isn't going to get confused with "veritone")

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +   docker tag hello-world veritone/hello-world:custom-tag
Delete `:custom-tag` since it is unnecessary and makes no sense in this context

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +   docker push veritone/hello-world:custom-tag
See previous comment about replacing the "veritone" account name. 

Delete `:custom-tag` since it is unnecessary and makes no sense.

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +  engine(id:"386e022f-edd1-46ec-b1cc-84d203a37250"){
This ID is different than the ID in all the previous examples - should be consistent with all the screen shots above

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +        executionPreferences: { priority: -20000 }
OH GOOD GOD - DELETE THIS PRIORITY!!!!!

You are telling the user to use a priority that is THOUSANDS of times higher than the highest priority they should ever use for anything. Remove the entire executionPreferences section and let them use the default priority.

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +        executionPreferences: { parentCompleteBeforeStarting: true, priority: -20000 }
delete priority!!!!

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +        executionPreferences: {    parentCompleteBeforeStarting: true, priority: -20000 }
delete priority

2021-07-19 20:25 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> +        executionPreferences: {    parentCompleteBeforeStarting: true, priority: -20000 }
delete priority!

2021-07-19 23:06 UTC, kevmurray requested changes

2021-07-19 23:06 UTC, kevmurray commented on src/docs/tutorials/pages/build-engine-using-developer-app/README.md
> -        executionPreferences: { parentCompleteBeforeStarting: true, priority: -20000 }
Need to put the "parentCompleteBeforeStarting" parameter back in - only delete the "priority".

Same for other "executionPreferences": Should not have "priority" field - if "Priority" is the only field, then delete the executionPreferences, but if there are other fields, just delete "priority"

2021-07-20 22:40 UTC, kevmurray approved these changes

2021-07-20 23:27 UTC, merged