install aiware on cluster tutorial
veritone/docs pull request #1281
Opened 2021-07-09 17:30 UTC by hm90121

2021-07-09 20:50 UTC, kevmurray requested changes

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +At a minimum three Linux Instances are required. One for Admin node ,worker node and aiWARE core functionalities . You can have more admin nodes and worker nodes deployed for better availability and
fix punctuation spacing

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +- Preferred Linux OS for nodes : Ubuntu 18.04 or Ubuntu 20.04, Red Hat 7 (Requires Docker EE)
Fix spacing in all of these: colons do not have spaces before them

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +- Minimum Requirement for Admin Node : 2 CPUs, 20Gb of Initial Storage Space, and 4GB of RAM
Gb = Gigabit
GB = Gigabyte
Do you really mean 20 Gigabits?

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +  Note :The above mentioned node requirements are just the starting points to initalize an aiWARE cluster .You will require additional system resources depending on the number of engines and run mode
fix punct

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +Response: This may take a minute or two .Here is the screenshot after successful installation
fix punct.

This is pervasive throughout the document - I'm not adding any more notes - please review all punctuation and fix so that all sentence and phrase punctuation has no space before it and one space after it.

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +![Terminal](terminal.png)
This image doesn't make sense - it shows you running as root and execute `sudo bash` so you can run as root - but you were already root. Fix this so you are not running as root so you can see the effect that `sudo bash` has

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
Where do I get a license key?

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +### Step 6: Validate Admin node
Where is step 5?

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +3.Go to http://:9000/edge/v1/version, or curl localhost:9000/edge/v1/version, for aiWARE Edge version information.
Where is step 2?

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +3.Go to http://:9000/edge/v1/version, or curl localhost:9000/edge/v1/version, for aiWARE Edge version information.
curl is a command - put it in a code block like all the other commands

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +3.Go to http://:9000/edge/v1/version, or curl localhost:9000/edge/v1/version, for aiWARE Edge version information.
what is the server name in the http address?

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +3.Go to http://:9000/edge/v1/version, or curl localhost:9000/edge/v1/version, for aiWARE Edge version information.
what is the protocol in the curl command URL?

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +1) Copy the below command to the terminal and press enter to update the package information from all of the configured sources
Why are some of the numbers like `1)` and some are like `1.` - make consistent

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
where do I get the license_key? Probably need to answer this at the top of the page as part of the initial setup

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_INIT_TOKEN=843489f6-ecff-4d19-95b0-2359eff60ec8   echo "AIWARE_INIT_TOKEN is $AIWARE_INIT_TOKEN"
This is illegal, put the echo on a new line

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_INIT_TOKEN=843489f6-ecff-4d19-95b0-2359eff60ec8   echo "AIWARE_INIT_TOKEN is $AIWARE_INIT_TOKEN"
Remove the hard-coded INIT_TOKEN and replace with something like `<ADMIN_INIT_TOKEN>`

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_INIT_TOKEN=843489f6-ecff-4d19-95b0-2359eff60ec8
Remove the hard-coded INIT_TOKEN and replace with something like `<ADMIN_INIT_TOKEN>`

2021-07-09 20:50 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +In the response you will have a cluster running all the the production aiWARE applications. To validate whether all the applications are successfully installed and running perfectly. Run `docker ps`
This command does not show whether something is "running perfectly", it just shows whether it is running or not - but it could be running with errors

2021-07-09 22:07 UTC, hm90121 commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
no idea,asked farye about it

2021-07-10 02:02 UTC, faryeyay requested changes
Please review the changes. One thing I'd suggest that I've started to do is to check the grammar and spelling using a tool such as Grammarly. It's helping me catch errors that I've written.

2021-07-10 02:02 UTC, faryeyay commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +843489f6-ecff-4d19-95b0-2359eff60ec8
The feedback from internal team members mentioned that there should be an explanation of the token. The fact that it should be a GUID and an alternate source for this such as https://www.uuidgenerator.net/

2021-07-14 17:25 UTC, kevmurray commented
@hm90121 , you are doing a lot of commits to this PR - please put into "draft mode" until you are done (assuming draft mode doesn't interfere with vercel)

2021-07-19 23:12 UTC, kevmurray approved these changes

2021-07-28 22:24 UTC, myoungerman commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
@hm90121 Did you find out where to get the license key from? Once Farye resolves this comment, I'll merge this PR, then add the changes you were unable to make.

2021-07-28 22:33 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
my understanding is that there's no such thing as a license key (it hasn't been implemented yet). The plan (discussed in slack) was to change this to `export AIWARE_LICENSE=trial` so we create the expectation of license keys someday. It won't actually do anything except serve as a placeholder for a real license key once we figure out what that looks like

2021-07-29 20:16 UTC, hm90121 commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
@myoungerman hi there i agree with @kevmurray ,right  now we are hardcoding AIWARE_LICENSE variable to trial so we can let them know later when the license information is available

2021-07-29 22:03 UTC, myoungerman commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
Gotcha, thanks for explaining!

2021-07-29 22:17 UTC, kevmurray commented on src/docs/tutorials/pages/install-aiware-on-cluster/README.md
> +export AIWARE_LICENSE=<LICENSE_KEY>
@hm90121 - please make the change. We've been discussing it in this thread, but I'm still waiting for you to update the documentation to actually say `export AIWARE_LICENSE=trial` instead of `export AIWARE_LICENSE=<LICENSE_KEY>` before approving.

2021-07-29 22:18 UTC, kevmurray requested changes
Please change the license key to "trial" in all three locations

2021-07-30 03:24 UTC, kevmurray approved these changes

2021-08-03 15:53 UTC, faryeyay approved these changes
lgtm

2021-08-05 16:22 UTC, myoungerman approved these changes

2021-08-05 16:22 UTC, merged