Claryty llc master
veritone/docs pull request #1351
Opened 2021-07-27 15:44 UTC by myoungerman

Copy of Abhishek's original PR that I've fixed merge conflicts in.

2021-07-27 19:18 UTC, kevmurray commented
Big change, may take a couple days - may also want to invite someone from the automate team to review since a lot of this seems related to automate

2021-07-27 21:03 UTC, myoungerman commented
@kevmurray Will do, who is on the automate team?

2021-07-28 00:12 UTC, kevmurray commented
I believe it is Andrew Pierno

2021-07-28 21:20 UTC, myoungerman commented
@kevmurray @wrannaman I opened this PR for Abhishek, and he says all of the technical changes are the markdown files in the folder (and subfolders) of **docs\automate-studio**. You can ignore the other files because they're just grammatical changes I've already reviewed and approved.

2021-07-29 15:57 UTC, wrannaman approved these changes

2021-07-29 22:52 UTC, kevmurray requested changes

2021-07-29 22:52 UTC, kevmurray commented on src/docs/automate-studio/getting-started/README.md
> +>>>>>>> 0bca0a50b307eacac138302fb3e692fdf6d50828
This is a conflict - resolve it

2021-07-29 22:52 UTC, kevmurray commented on src/docs/automate-studio/getting-started/README.md
> +1. Navigate to [automate.veritone.com](https://automate.veritone.com), click on the `Add New` button in the upper left corner of that page.
no such button: `Add New`

2021-07-29 22:52 UTC, kevmurray commented on src/docs/automate-studio/getting-started/README.md
> +- Press Ctrl+Z to undo any action.
Remove spaces between these lines to make it a list instead of separate paragraphs?

2021-07-29 22:52 UTC, kevmurray commented on src/docs/automate-studio/getting-started/README.md
> +2. Click on the ballot-box square at the left edge of the aiware.in node to run the flow.
"ballot-box": this is not a term I'm familiar with for GUIs. Shouldn't this just be "the button", maybe with a screen shot if it is confusing

2021-07-29 22:52 UTC, kevmurray commented on src/docs/automate-studio/working-with-flows/README.md
> +>>>>>>> 0bca0a50b307eacac138302fb3e692fdf6d50828
Resolve this conflict

2021-08-06 16:57 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +2. Click on the ballot-box square at the left edge of the aiware.in node to run the flow.
Fixed

2021-08-06 16:57 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +- Press Ctrl+Z to undo any action.
Fixed

2021-08-06 16:58 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +1. Navigate to [automate.veritone.com](https://automate.veritone.com), click on the `Add New` button in the upper left corner of that page.
Fixed

2021-08-06 16:59 UTC, ClarytyLLC commented on src/docs/automate-studio/working-with-flows/README.md
> +>>>>>>> 0bca0a50b307eacac138302fb3e692fdf6d50828
Resolved.

2021-08-06 17:03 UTC, ClarytyLLC commented on src/docs/automate-studio/getting-started/README.md
> +>>>>>>> 0bca0a50b307eacac138302fb3e692fdf6d50828
Resolved.

2021-08-06 17:17 UTC, myoungerman commented
@kevmurray Can you confirm that Abhishek has fixed everything mentioned in your comments?

2021-08-06 17:28 UTC, closed without merging

2021-08-06 17:28 UTC, myoungerman commented
Closing this PR since Abhishek has made the necessary fixes in a new PR (since he's unable to commit to this one) 

https://github.com/veritone/docs/pull/1433