Active directory docs
veritone/docs pull request #1601
Opened 2021-09-13 17:16 UTC by myoungerman

2021-09-13 18:10 UTC, anetroger requested changes
I have reviewed up to half of the file. Please, be consistent when you write step results and when you refer to UI terms. Delete all screenshots that can be written as step results and replace them by step results. Make sure that you put context first, as in the style guide. When you do that for all files, please resubmit the PR.

2021-09-13 18:10 UTC, anetroger commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +      Your newly created app should appear in the **Display name** list.
Delete 'should'. Present tense is preferred.

2021-09-13 18:10 UTC, anetroger commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +1. Select the **Endpoints** tab. The **Endpoints** panel appears.
Separate line for step results

2021-09-13 18:10 UTC, anetroger commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +1. Select **+ New Client Secret**. An **Add a client secret** panel appears.
Separate line for step results

2021-09-13 18:10 UTC, anetroger commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +1. Select **None Selected** under **Users**. The **Users** panel appears on the right.
Separate line for step results - please review this file for all occurrences of step results.

2021-09-13 18:10 UTC, anetroger commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +      The **Provisioning** page loads.
Be consistent - use 'appears' in all occurrences.

2021-09-14 15:11 UTC, myoungerman commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +This tutorial shows you how to configure SCIM (System for Cross-Domain Identity Management) endpoints and create an aiWare organization, Azure Active Directory (AD) application, and users.
fixed

2021-09-14 15:11 UTC, myoungerman commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +      The app overview page loads and show your app's properties.
fixed

2021-09-14 15:11 UTC, myoungerman commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +      Your newly created app should appear in the **Display name** list.
fixed

2021-09-14 15:11 UTC, myoungerman commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +1. Select the **Endpoints** tab. The **Endpoints** panel appears.
fixed

2021-09-14 15:11 UTC, myoungerman commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +1. Select **+ New Client Secret**. An **Add a client secret** panel appears.
fixed

2021-09-14 15:11 UTC, myoungerman commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +1. Select **None Selected** under **Users**. The **Users** panel appears on the right.
fixed

2021-09-14 15:11 UTC, myoungerman commented on src/docs/tutorials/pages/azure-ad-application-and-openid.md
> +      The **Provisioning** page loads.
fixed

2021-09-14 21:14 UTC, anetroger commented
Approving this PR as per Mitchell request.

2021-09-14 21:20 UTC, anetroger approved these changes
Approving the PR without reviewing changes.

2021-09-14 21:20 UTC, merged