DOC-2
veritone/docs pull request #1604
Opened 2021-09-13 23:41 UTC by anetroger

Changes to the documentation page: https://docs.veritone.com/#/aiware/manage/maintenance?id=upgrading-aiware
DOC-2 in Jira

2021-09-13 23:46 UTC, anetroger reviewed
bad formatting, please request changes

2021-09-14 15:35 UTC, myoungerman commented on src/docs/aiware/manage/maintenance.md
> +To upgrade to aiWARE, first, stop the Docker stack and remove Docker containers. Then update run modes, export the configuration that you need, and then re-run the installation.
Change "To upgrade to aiWARE" to "To upgrade aiWARE"

2021-09-14 15:37 UTC, myoungerman commented on src/docs/aiware/manage/maintenance.md
> +To upgrade to aiWARE, first, stop the Docker stack and remove Docker containers. Then update run modes, export the configuration that you need, and then re-run the installation.
Remove the second "then"

2021-09-14 15:37 UTC, myoungerman commented on src/docs/aiware/manage/maintenance.md
> +* On the terminal, copy and paste the following commands.
Change "On" to "In"

2021-09-14 15:37 UTC, myoungerman commented on src/docs/aiware/manage/maintenance.md
> +# Installs the upgrade
Change "Installs" to "Install"

2021-09-14 15:38 UTC, myoungerman requested changes
Left comments w/ necessary changes :)

2021-09-14 15:47 UTC, anetroger commented on src/docs/aiware/manage/maintenance.md
> +To upgrade to aiWARE, first, stop the Docker stack and remove Docker containers. Then update run modes, export the configuration that you need, and then re-run the installation.
Accepted the first comment, thanks for catching that. 
The separation of sentences is because the commands are doing different things here: first, we have command for Docker, and then we issue other commands for the installation.

2021-09-14 15:55 UTC, anetroger commented on src/docs/aiware/manage/maintenance.md
> +# Installs the upgrade
This is a comment and it is telling users what the command does: it 'installs' whatever it installs. the same with the comments 'exports' and 'validates'

2021-09-14 15:55 UTC, anetroger commented on src/docs/aiware/manage/maintenance.md
> +To upgrade to aiWARE, first, stop the Docker stack and remove Docker containers. Then update run modes, export the configuration that you need, and then re-run the installation.
Replaced with 'next'

2021-09-14 16:02 UTC, anetroger commented on src/docs/aiware/manage/maintenance.md
> +* On the terminal, copy and paste the following commands.
Changed.

2021-09-14 16:04 UTC, anetroger commented on src/docs/aiware/manage/maintenance.md
> +# Installs the upgrade
Thanks for the suggestion - this can be seen two ways: a comment or an instruction. Since you pointed that out, framing it as a comment might be odd from the user perspective, so I changed this and all other comments as instructions. (export and validate, above this comment).

2021-09-14 16:11 UTC, myoungerman approved these changes

2021-09-14 16:11 UTC, merged