AIW-3853 Flow bounty page refresh
veritone/docs pull request #344
Opened 2020-10-17 08:58 UTC by aMacDawg

deleted the flow bounty cards section

2020-10-17 18:53 UTC, kfiry requested changes

2020-10-17 18:53 UTC, kfiry commented on src/docs/automate-studio/flow-bounties/README.md
> +Check out our list of Automate Studio flow template projects and claim the flow template that is interesting for you to build! You can find the list of flows and claim one at a time with this [link](
Wrong link. Should be: https://github.com/veritone/automate-flow-templates/projects/1
BUT ACTUALLY -- let's remove this section altogether. There are TWO more references to the wishlist on this page, both with the wrong link. Let's just fix the link for those two references, and then no need for this section anymore.

2020-10-18 08:05 UTC, aMacDawg commented on src/docs/automate-studio/flow-bounties/README.md
> +Check out our list of Automate Studio flow template projects and claim the flow template that is interesting for you to build! You can find the list of flows and claim one at a time with this [link](
Got it, I updated the file with the correct url in the two spots and deleted the bottom section. Do we want to remove the sidebar references to each flow status as well?

2020-10-18 10:56 UTC, kfiry commented on src/docs/automate-studio/flow-bounties/README.md
> +Check out our list of Automate Studio flow template projects and claim the flow template that is interesting for you to build! You can find the list of flows and claim one at a time with this [link](
Yes to remove the sidebar links. 
And also, the "Get Started" link at the end is just sending back to the same page...

2020-10-19 08:18 UTC, aMacDawg commented on src/docs/automate-studio/flow-bounties/README.md
> +Check out our list of Automate Studio flow template projects and claim the flow template that is interesting for you to build! You can find the list of flows and claim one at a time with this [link](
thanks, fixed. Sidebar updated as well. I would like to merge [PR/343](https://github.com/veritone/docs/pull/343) in first

2020-10-23 23:12 UTC, closed without merging