Dev/auth explained
veritone/docs pull request #937
Opened 2021-05-11 15:46 UTC by LevLevenberg

2021-05-11 15:54 UTC, kfiry requested changes

2021-05-11 15:54 UTC, kfiry commented on src/docs/automate-studio/working-with-flows/README.md
> +    - [Run via HTTP with Authentication](#run-via-http-with-authentication)
You can't run without auth. No need for a new section, just explain the auth part in the "Run Flow via HTTP" section.

2021-05-12 06:21 UTC, LevLevenberg commented on src/docs/automate-studio/working-with-flows/README.md
> +    - [Run via HTTP with Authentication](#run-via-http-with-authentication)
done

2021-05-12 16:09 UTC, kfiry approved these changes

2021-05-12 16:10 UTC, merged